### ISSUE TITLE
Incorrect deprecatedrpc entry

### ISSUE THREAD

**Issue by achow101** [jlopp/bitcoin-core-config-generator#24]
`deprecatedrpc=1` is incorrect. It is not a generic switch that enables all deprecated RPCs. Rather you need to specify exactly what RPCs that are deprecated that you want to enable. For example (in a future release of Bitcoin Core), you would do `deprecatedrpc=validateaddress` in order to enable deprecated functionality in `validateaddress`.

**Comment by jlopp** [comment]
this should be fixed as of  97cb431
