### ISSUE TITLE
Update dbcache default to 450

### ISSUE THREAD

**Issue by Xtrimmer** [jlopp/bitcoin-core-config-generator#31]
Per the bitcoin core [release notes for version 0.14.1](https://github.com/bitcoin/bitcoin/blob/f8feaa4636260b599294c7285bcf1c8b7737f74e/doc/release-notes/release-notes-0.14.1.md#utxo-memory-accounting), the default **-dbcache** has been changed to **450MiB**. Currently the bitcoin core config generator uses 300 as the default.

**Comment by jlopp** [comment]
Fixed by #32
