### ISSUE TITLE
Improving descriptors of config options, predefined config for connecting Lightning node

### ISSUE THREAD

**Issue by michaelfolkson** [jlopp/bitcoin-core-config-generator#34]
There are a couple of us on Justin Moen's BUIDL Bootcamp Slack that would like to contribute to this project. As it stands, it is a great start but we feel that some of the one line descriptors of the config options could be improved and having a predefined config for setting up a lightning node would also be useful. We'd need some help from someone who understands what all the config options do though. Could someone provide this help? If not, could you recommend someone else who doesn't necessarily contribute to this project who may be able to help?

**Comment by jlopp** [comment]
Sure, FYI I took most of the descriptions from the "help" output that is mostly defined in https://github.com/bitcoin/bitcoin/blob/master/src/init.cpp

If you can't get a hold of me, I'd think that the Bitcoin Core Slack / Core Dev IRC would be good places to ask for further details. My handle on Slack is @lopp
