### ISSUE TITLE
RPC cookie directory setting misleading

### ISSUE THREAD

**Issue by bolatovumar** [jlopp/bitcoin-core-config-generator#37]
rpccookiefile settings is set to ~/.bitcoin/ by default (for Linux) which makes it look like if a user wanted to change the location of the RPC cookie, you would have to just specify a new folder for it (something like ~/.bitcoin/my-rpc-cookie-dir/). This is not the case, however. You need to point exactly to a cookie file (something like ~/.bitcoin/.cookie or ~/.bitcoin/my-rpc-cookie-dir/.cookie).

Would changing the default value that is being displayed to ~/.bitcoin/.cookie make sense? I think it could help n00bs like myself.

I'm willing to submit a PR for this.

**Comment by jlopp** [comment]
Ah OK, that should be a simple fix to change the default value in one of the json files. If you can figure out how to do it, feel free, otherwise I'll get around to it when I have some time.
