### ISSUE TITLE
The option 'conf' should not be used inside the bitcoin.conf file

### ISSUE THREAD

**Issue by gijswijs** [jlopp/bitcoin-core-config-generator#43]
I found this out the hard way, unrelated to this awesome bitcoin.conf file generator.

I should've know better, because it's in the core documentation.

> All command-line options (**except for** -?, -help, -version and -**conf**) may be specified in a configuration file

source: https://github.com/bitcoin/bitcoin/blob/master/doc/bitcoin-conf.md

So if you want to have your bitcoin.conf file at a different location, have a bitcoin.conf file at the default location which only specifies `includeconf` pointing to the different location, relative to the data directory.

**Comment by jlopp** [comment]
Correct, though what do you propose I change? Add some additional explanation in the UI that if you used this option, all other options need to be in the other config file?

**Comment by gijswijs** [comment]
Yeah, just remove the option from the generator.

Off topic: Your op-ed on CW for Bitcoin Magazine is an amazing piece of work. Thank you for that.

**Comment by jlopp** [comment]
Great, thanks!
