### ISSUE TITLE
Help to deploy.

### ISSUE THREAD

**Issue by Jetro-Costa** [jlopp/bitcoin-core-config-generator#46]
I need help to deploy the application, thank you.

**Comment by jlopp** [comment]
If you're running your own fork of this, make sure you have github pages enabled for the project.

Then all you need to do is run "npm run build" in the root directory of the project and follow the instructions for how to push the built application.

**Comment by jlopp** [comment]
You'll also want to update a few fields in package.json so that it matches your fork's name and URL

**Comment by Jetro-Costa** [comment]
Thakn a lot man.
