### ISSUE TITLE
blockfilterindex NOT set if one chooses peerblocksfilter

### ISSUE THREAD

**Issue by scgbckbone** [jlopp/bitcoin-core-config-generator#56]
If one chooses `peerblocksfilter` option in network section, config generator should automatically add `blockfilterindex` too, or at least warning in text that this option MUST be selected either for it to work.

Otherwise `Error: Cannot set -peerblockfilters without -blockfilterindex`

**Comment by jlopp** [comment]
Thanks; fixed has been deployed. The peerblockfilter option now notes the dependency and if the option is enabled it forces blockfilterindex value to 1.
