### ISSUE TITLE
Actual official config docs

### ISSUE THREAD

**Issue by gkucmierz** [jlopp/bitcoin-core-config-generator#67]
Many of your settings in this app are deprecated.

Do you know where can I find actual official bitcoin conf documetation?

**Comment by jlopp** [comment]
Can you be more specific? I update this app with each release of Bitcoin Core to ensure that all options are currently valid.

The "official" documentation (what I use to generate the list of options) is found by running the "help" command against Bitcoin Core:

`bitcoind --help --help-debug`

**Comment by gkucmierz** [comment]
I think I opened old version from some link.

Sorry for bothering you then.
