### ISSUE TITLE
Bitcoin Core v26 changes

### ISSUE THREAD

**Issue by tadeubas** [jlopp/bitcoin-core-config-generator#68]
Add the new `v2transport` config, as listed on the release https://bitcoincore.org/en/releases/26.0/

**Comment by jlopp** [comment]
$ ./bitcoin-25.0/bin/bitcoind --help --help-debug|grep "^  -" | sort > ./options-25.txt
$ ./bitcoin-26.0/bin/bitcoind --help --help-debug|grep "^  -" | sort > ./options-26.txt
```
$ diff -C 0 ./options-25.txt ./options-26.txt
*** ./options-25.txt	2023-12-10 13:03:33.635209613 -0500
--- ./options-26.txt	2023-12-10 13:04:15.866753595 -0500
+   -acceptstalefeeestimates
+   -allowignoredconf
-   -sandbox=<mode>
+   -v2transport
```
